@startuml

class ListeurCategorie
class ListeurSalle
class PanelListeurCategorie
class ControleurExamen

class JPanel <<Java>>
class JScrollPane <<Java>>
interface MouseListener <<Java>>

Class Categorie{
    static void createTable()
    static void deleteTable()
    static void findById(int id)
    static void getListCategorie()
    void save()
}

ListeurCategorie --|> JPanel
ListeurCategorie --> ControleurExamen
ListeurCategorie --> JScrollPane
ListeurCategorie --> PanelListeurCategorie
ListeurCategorie --> Categorie :listCategorie
ListeurCategorie --> PanelListeurCategorie : liste_PanelListeur

ListeurSalle --|> JPanel
ListeurSalle --> ControleurExamen
ListeurSalle --> JScrollPane

PanelListeurCategorie --|> JPanel
PanelListeurCategorie --> ListeurCategorie
PanelListeurCategorie --> JPanel : list_jp_groupe
PanelListeurCategorie --> MouseListener
PanelListeurCategorie --> Categorie


class ControleurCaseSalle
class ControleurRadioBoutons
class ControleurSauvegardeSalle
class ControleurBoutonsPartieSalle
class Salle

class JButton <<Java>>
class Color <<Java>>
interface ActionListener <<Java>>

ControleurCaseSalle --|> JButton
ControleurCaseSalle ..|> ActionListener
ControleurCaseSalle --> Color
ControleurCaseSalle --> Salle : modele

ControleurRadioBoutons --|> JPanel
ControleurRadioBoutons ..|> ActionListener

ControleurSauvegardeSalle --|> JButton
ControleurSauvegardeSalle ..|> ActionListener

ControleurBoutonsPartieSalle --|> JPanel
ControleurBoutonsPartieSalle --> JButton
ControleurBoutonsPartieSalle --> Salle : modele

class ControleurBouttonConfCreationCateg
class ControleurConfirmerImportation
class ControleurCreerNouvelleCateg
class ControleurImportationListe
class ControleurListeDeroulanteCateg
class DeroulOptionTriCateg
class vueCreationCateg
class VueImportation
class VueEtudiant
class VueChargement
class DifListeurEtu

class JTextField <<Java>>
class JFileChooser <<Java>>
class JComboBox <<Java>>

ControleurBouttonConfCreationCateg --|> JButton
ControleurBouttonConfCreationCateg ..|> ActionListener
ControleurBouttonConfCreationCateg --> JTextField
ControleurBouttonConfCreationCateg --> vueCreationCateg
ControleurBouttonConfCreationCateg --> ControleurListeDeroulanteCateg

ControleurConfirmerImportation --|> JButton
ControleurConfirmerImportation ..|> ActionListener
ControleurConfirmerImportation --> VueImportation
ControleurConfirmerImportation --> VueEtudiant
ControleurConfirmerImportation --> VueChargement

ControleurCreerNouvelleCateg --|> JButton
ControleurCreerNouvelleCateg ..|> ActionListener
ControleurCreerNouvelleCateg --> vueCreationCateg
ControleurCreerNouvelleCateg --> ControleurListeDeroulanteCateg

ControleurImportationListe --|> JButton
ControleurImportationListe ..|> ActionListener
ControleurImportationListe --> VueImportation
ControleurImportationListe --> JFileChooser
ControleurImportationListe --> VueEtudiant

ControleurListeDeroulanteCateg --|> JComboBox
ControleurListeDeroulanteCateg --> Categorie : listeCateg

DeroulOptionTriCateg --|> JComboBox
DeroulOptionTriCateg --> DifListeurEtu

class Examen
class HashMap <<Java>>

ControleurExamen --> Examen
ControleurExamen --> JButton
ControleurExamen --> HashMap : HashMap<JButton,Groupe>
ControleurExamen --> HashMap : HashMap<JButton,Categorie>
ControleurExamen --> JTextField
ControleurExamen --> Groupe : ArrayList<ArrayList<Groupe>>

class ConstructeurDataEtudiant
class ConstructeurListeModelCategorie
class ControleurSuprListe
class ListenerDeRefresh

class JTree <<Java>>

ConstructeurDataEtudiant --> Groupe : ArrayList<Groupe>

ConstructeurListeModelCategorie --> Categorie : ArrayList<Categorie>

ControleurSuprListe --|> JButton
ControleurSuprListe ..|> ActionListener
ControleurSuprListe --> JTree

ListenerDeRefresh --> DifListeurEtu

class AfficheurTree
class LigneEtudiant
class PanelCheckBox
class PanelListeurEtu

class JSplitPan <<Java>>
class JTable <<Java>>
class JLabel <<Java>>

AfficheurTree --|> JPanel
AfficheurTree --> JTree
AfficheurTree --> DifListeurEtu
AfficheurTree --> DeroulOptionTriCateg
AfficheurTree --> JTextField

DifListeurEtu --|> JSplitPan
DifListeurEtu --> JScrollPan : jspLeft
DifListeurEtu -->JScrollPan : jspRight
DifListeurEtu --> ConstructeurListeModelCategorie
DifListeurEtu --> ConstructeurDataEtudiant
DifListeurEtu --> JTable
DifListeurEtu --> AfficheurTree
DifListeurEtu --> Etudiant : ArrayList<Etudiant>

LigneEtudiant --|> JPanel
LigneEtudiant --> Etudiant
LigneEtudiant --> JTextField

PanelCheckBox --|> JPanel
PanelCheckBox --> JTree

PanelGauche --|> JPanel
PanelGauche --> JScrollPan
PanelGauche --> JLabel
PanelGauche --> ControleurSuprListe
PanelGauche --> ControleurCreerNouvelleCateg

PanelListeurEtu --|> JPanel
PanelListeurEtu --> DifListeurEtu


class DBConnection <<Active Record>>{
static synchronized Connection getConnection()
static void setNomDb()
}

class Connection <<Java>>

class Etudiant <<Active Record>>{
static void createTable()
static void deleteTable()
static void findById()
void save()
void delete()
}

class EtudiantGroupe <<Active Record>>{
static void createTable()
static void deleteTable()
static void ajouterEtudiantAUnGroupe(IdEtudiant,IdGroupe)
static void listeGroupePourEtudiant(idEtudiant)
}

class Groupe <<Active Record>>{
static void createTable()
static void deleteTable()
static Groupe findById(int id)
static ArrayList<Groupe> listGroupe()
void delete()
void save()
}

class GroupeCategorie <<Active Record>>{
static void createTable()
static void deleteTable()
static listGroupePourCategorieiD(idCategorie)
}

class Particularite <<Active Record>>{
static void createTable()
static void deleteTable()
void save()
void delete()
Particularite findById()
}

class ParticulariteEtudiant <<Active Record>>{
static void createTable()
static void deleteTable()
void listParticularitePourEtudiant(idEtudiant)
}

class Place <<Active Record>>{
static void createTable()
static void deleteTable()
void save()
void delete()
static Place findById(idPlace)
}

class Salle <<Active Record>>{
static void createTable()
static void deleteTable()
void save()
void delete()
static Salle findById(idSalle)
}

class TypePlace <<Active Record>>{
static void createTable()
static void deleteTable()
void save()
void delete()
TypePlace findById(idTypePlace)
}

interface Comparable <<Java>>
class Observable <<Java>>
TypePlace --> DBConnection
Place --> DBConnection
EtudiantGroupe --> DBConnection
GroupeCategorie--> DBConnection
Particularite --> DBConnection
ParticulariteEtudiant --> DBConnection
Salle --|> Observable
Salle --> Place : "places"
Salle --> DBConnection
Etudiant ..|> Comparable
DBConnection --> Connection

class ExportEtudiant
class ImportEtudiant

Examen --> Etudiant : "HashMap<Etudiant,String>"
Examen --> Salle : "ArrayList<Salle>"
Examen --> Place : "HashMap<Salle, HashMap<Place, Etudiant>>"
Examen --|> Observable

class Boutton_Annuler
class Boutton_Confirmer
class Frame_Popup

Boutton_Annuler --|> JButton
Boutton_Annuler ..|> ActionListener
Boutton_Annuler --> Frame_Popup

Boutton_Confirmer --|> JButton
Boutton_Confirmer ..|> ActionListener
Boutton_Confirmer --> Frame_Popup

Frame_Popup --|> JFrame
Frame_Popup --> Categorie
Frame_Popup --> JTextField
Frame_Popup --> Boutton_Confirmer
Frame_Popup --> Boutton_Annuler

class Indicateur

class CreationSalleDialog
class CreationSalleDialogInfos

class JDialog <<Java>>
class JSpinner <<Java>>

CreationSalleDialog --|> JDialog
CreationSalleDialog --> CreationSalleDialogInfos
CreationSalleDialog --> JTextField
CreationSalleDialog --> JLabel
CreationSalleDialog --> JSpinner
CreationSalleDialog --> JButton
Indicateur--|> JPanel

class TabbedPanDesign
class BasicTabbedPaneUI <<Java>>

TabbedPanDesign --|> BasicTabbedPaneUI

class VueOngletModules
class VueSalle

VueOngletModules --|> JPanel
VueOngletModules ..|> Observer
VueOngletModules --> JTabbedPan
VueOngletModules --> VueExamen
VueOngletModules --> VueSalle

VueSalle --|> JPanel
VueSalle ..|> Observer
VueSalle --> JScrollPan
VueSalle --> JPanel
VueSalle --> Salle

vueCreationCateg --|> JFrame
VueEtudiant --|> JPanel
VueEtudiant ..|> Observer
VueEtudiant --> ControleurImportationListe
VueEtudiant --> ControleurListeDeroulanteCateg
VueEtudiant --> DifListeurEtu
VueEtudiant --> PanelListeurEtu
VueEtudiant --> JTextField

VueImportation --|> JFrame
VueImportation --> ControleurConfirmerImportation
VueImportation --> ControleurCréerNouvelleCateg
VueImportation --> ControleurListeDeroulanteCateg

class VueContrainte
class VueCreation
class VueGroupeParticipant
class VueInfoExamen
class VueSallePriorite

VueContrainte --|> JPanel
VueCreation --|> JPanel
VueCreation --> ControleurExamen
VueCreation --> VueInfoExamen
VueCreation --> VueGroupeParticipant
VueCreation --> VueSallePriorite
VueCreation --> VueContrainte

VueExamen --|> JPanel
VueExamen ..|> Observer
VueExamen --> Examen
VueExamen --> ControleurExamen
VueGroupeParticipant --|> JPanel
VueGroupeParticipant --> ControleurExamen
VueGroupeParticipant --> ListeurCategorie
VueInfoExamen --|> JPanel
VueInfoExamen --> Examen
VueInfoExamen --> ControleurExamen
VueSallePriorite --|> JPanel
VueSallePriorite --> ControleurExamen




















@enduml